# Generated by Django 5.2.14 on 2026-05-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherprofile_created_at_alter_teacherprofile_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
    ]
