# Generated by Django 5.2.14 on 2026-05-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='class_name',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='teacher.class'),
        ),
    ]
