# Generated by Django 5.2.14 on 2026-05-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacherprofile_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='class_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='teacher.class'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='teacher.subject'),
        ),
    ]
