# Generated by Django 5.2.14 on 2026-05-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_teacherprofile_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutions', to='teacher.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutions', to='teacher.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutions', to='teacher.teacherprofile')),
            ],
        ),
    ]
