# Generated by Django 5.2.14 on 2026-05-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_tution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tution',
            name='scheduled_time',
        ),
    ]
