# Generated by Django 5.2.14 on 2026-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_remove_tution_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tution',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tution',
            name='price_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
