# Generated by Django 5.2.14 on 2026-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_tution_hours_tution_price_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
