# Generated by Django 5.2.14 on 2026-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacherprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='teacher.subject'),
        ),
    ]
