# Generated by Django 5.2.14 on 2026-05-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_teacherprofile_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='trial_end',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='trial_start',
        ),
    ]
