# Generated by Django 5.2.14 on 2026-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_remove_teacherprofile_trial_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='teacher.subject'),
        ),
    ]
