# Generated by Django 5.2.14 on 2026-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_tuitionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='cv',
            field=models.FileField(upload_to='teacher_cv/'),
        ),
    ]
