# Generated by Django 5.2.14 on 2026-06-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_tution_studenttution_tuition_and_more'),
        ('teacher', '0017_alter_teacherprofile_cv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tution',
            new_name='Tuition',
        ),
        migrations.RenameField(
            model_name='tuitionapplication',
            old_name='tution',
            new_name='tuition',
        ),
        migrations.AlterUniqueTogether(
            name='tuitionapplication',
            unique_together={('student', 'tuition')},
        ),
    ]
