# Generated by Django 5.2.14 on 2026-06-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0018_rename_tution_tuition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('video_room_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=True)),
                ('tution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_groups', to='teacher.tuition')),
            ],
        ),
    ]
