# Generated by Django 5.2.14 on 2026-06-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachgroup',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='teachgroup',
            old_name='tution',
            new_name='tuition',
        ),
    ]
