# Generated by Django 5.2.14 on 2026-06-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_tution_studenttution_tuition_and_more'),
        ('teach_group', '0002_rename_description_teachgroup_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teach_group.teachgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='student.studentprofile')),
            ],
            options={
                'unique_together': {('group', 'student')},
            },
        ),
    ]
