# Generated by Django 5.2.14 on 2026-05-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
