# Generated by Django 5.2.14 on 2026-05-28 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_profile_picture'),
        ('teacher', '0012_teacherprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.studentprofile')),
                ('tution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teacher.tution')),
            ],
            options={
                'unique_together': {('student', 'tution')},
            },
        ),
    ]
