# Generated by Django 5.2.14 on 2026-05-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studenttution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttution',
            name='hours',
        ),
    ]
