# Generated by Django 5.2.14 on 2026-05-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studenttution_hours'),
        ('teacher', '0014_remove_teacherprofile_trial_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student.studentprofile')),
                ('tution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teacher.tution')),
            ],
            options={
                'unique_together': {('student', 'tution')},
            },
        ),
    ]
