# Generated by Django 5.2.14 on 2026-06-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_tuitionapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuitionApplication',
        ),
    ]
