# Generated by Django 5.2.14 on 2026-06-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_delete_tuitionapplication'),
        ('teacher', '0017_alter_teacherprofile_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttution',
            old_name='tution',
            new_name='tuition',
        ),
        migrations.AlterUniqueTogether(
            name='studenttution',
            unique_together={('student', 'tuition')},
        ),
    ]
