# Generated by Django 5.2.14 on 2026-06-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_tution_studenttution_tuition_and_more'),
        ('teacher', '0018_rename_tution_tuition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentTution',
            new_name='StudentTuition',
        ),
    ]
