# Generated by Django 5.2.14 on 2026-07-04 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_studenttuition_tuition'),
        ('teacher', '0018_rename_tution_tuition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttuition',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teacher.tuition'),
        ),
    ]
