# Generated by Django 5.2.14 on 2026-06-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_customuser_id_alter_passwordresetotp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
